### ISSUE TITLE
Auto reload on file change in GitPod Dev Mode

### ISSUE THREAD

**Issue by LvckyAPI** [uhmarlon/guess-the-thing#14]
## User Story:
Currently, the Docker container is simply started up in the GitPod setup.
If you now change a file, everything remains as it was when the container was started.

In future, the system should also restart or react to changes after a file change.

## Mögliche Behebung durch:
- docker host mount

## ToDo:
- [ ] Create another Dockerfile, which simply starts the project
- [ ] create a host mount in a new docker-compose.dev.yml

## Finished?
- [ ] Function tested
- [ ] Pull request set to ready
- [ ] All setups work
    - [ ] Production Mode using Docker Compose
    - [ ] Development Mode using GitPod
    - [ ] Development Mode using local NodeJS

**Comment by uhmarlon** [comment]
Thank you for your suggestion. Currently, we don't offer direct support for GitPod integration. Your idea of using a Docker host mount seems promising. Feel free to implement this solution, and contributions are always welcome.
