### ISSUE TITLE
Gamemode Guess the License plate

### ISSUE THREAD

**Issue by LvckyAPI** [uhmarlon/guess-the-thing#16]
## User Story:
We need a new game mode.  
“Guess the license plate”.  

Concept:
There is a list of German license plates in the backend.  
To be more precise, a JSON array with license plate abbreviation and corresponding fully spelled out city/district.  

The frontend renders a license plate as a vector graphic.  
The abbreviation is then rendered on top of it. The rest remains empty or is filled randomly.

## ToDo:
- [x] get JSON list for license plates
- [x] implement it in the backend socket endpoint
- [ ] get license plate vector graphic
- [ ] render abbreviations on license plate
- [x] copy text input and game behavior from guess the flag

## Finished?
- [ ] Function tested
- [ ] Pull request set to ready
- [ ] All setups work
    - [ ] Production Mode using Docker Compose
    - [ ] Development Mode using GitPod
    - [ ] Development Mode using local NodeJS

**Comment by uhmarlon** [comment]
New Code Base
